Pass options via a json file instead of command line arguments (#167)
Summary:
Fixes https://github.com/facebook/mariana-trench/issues/164

- First, the shim parses the arguments and creates a JSON file having those arguments
- Then the shim passes the JSON file path to the cpp
- The CPP code parses that JSON file and uses the arguments

Pull Request resolved: https://github.com/facebook/mariana-trench/pull/167

Test Plan:
```
$ buck run //fbandroid/native/mariana-trench/shim:shim -- \
  --apk-path=$HOME/mariana-trench-apk/fbandroid/fblite_latest.apk \
  --output-directory=/tmp/output \
  --verbosity 2
2024-07-24 08:10:13 INFO Arguments: {
  "apk-directory" : "/tmp/tmp26n3_vb1_apk",
  "apk-path" : "/home/arthaud/mariana-trench-apk/fbandroid/fblite_latest.apk",
  "dex-directory" : "/tmp/tmp4yc83fu1_dex",
  "lifecycles-paths" : "/data/users/arthaud/fbsource/fbandroid/native/mariana-trench/facebook/internal-configuration/lifecycles.json",
  "maximum-source-sink-distance" : 7,
  "model-generator-configuration-paths" : "/data/users/arthaud/fbsource/fbandroid/native/mariana-trench/facebook/internal-configuration/default_generator_config.json",
  "model-generator-search-paths" : "/data/users/arthaud/fbsource/fbandroid/native/mariana-trench/facebook/internal-configuration;/data/users/arthaud/fbsource/fbandroid/native/mariana-trench/configuration",
  "output-directory" : "/tmp/output/",
  "repository-root-directory" : "/data/users/arthaud/fbsource/",
  "rules-paths" : "/data/users/arthaud/fbsource/fbandroid/native/mariana-trench/facebook/internal-configuration/rules.json",
  "shims-paths" : "/data/users/arthaud/fbsource/fbandroid/native/mariana-trench/facebook/internal-configuration/shims.json",
  "source-root-directory" : "/data/users/arthaud/fbsource/",
  "system-jar-paths" : "/opt/android/sdk_DEFAULT/platforms/android-29/android.jar;/opt/android/sdk_DEFAULT/platforms/android-29/optional/org.apache.http.legacy.jar;fbandroid/apps/mapillary/bucklibs/android-lifecycle-extensions/common-1.1.1.jar;fbandroid/apps/mapillary/bucklibs/com.vladsch.flexmark/flexmark-all-0.20.0-lib.jar;fbandroid/apps/mapillary/bucklibs/guava-android/guava-27.0.1-android.jar;fbandroid/apps/mapillary/bucklibs/mapbox-java-core/mapbox-java-core-2.0.0-beta.3.jar;fbandroid/apps/mapillary/bucklibs/mapbox-java-geojson/mapbox-java-geojson-2.2.10.jar;fbandroid/apps/mapillary/bucklibs/mapbox-java-services/mapbox-java-services-2.0.0-beta.3.jar;fbandroid/apps/mapillary/bucklibs/mapbox-sdk-geojson/mapbox-sdk-geojson-4.6.0.jar;fbandroid/apps/mapillary/bucklibs/mapbox-sdk-services/mapbox-sdk-services-3.0.1.jar;fbandroid/apps/mapillary/bucklibs/mapbox-sdk-turf/mapbox-sdk-turf-4.7.0.jar;fbandroid/apps/mapillary/bucklibs/oauth-signpost/signpost-commonshttp4-1.2.1.2.jar;fbandroid/apps/mapillary/bucklibs/oauth-signpost/signpost-core-1.2.1.2.jar;fbandroid/apps/mapillary/bucklibs/org.greenrobot/eventbus/eventbus-3.0.0.jar;fbandroid/apps/mapillary/bucklibs/rxkotlin/rxkotlin-2.3.0.jar;fbandroid/apps/mapillary/bucklibs/support-v4/collections-28.0.0.jar;fbandroid/first-party/java/androidsdk/ads/libs/bdthriftlib.jar;fbandroid/first-party/java/mapillary-sdk/sdk/bucklibs/moshi-kotlin/moshi-kotlin-1.9.1.jar;fbandroid/first-party/java/mapillary-sdk/sdk/bucklibs/moshi/moshi-1.9.1.jar;fbandroid/first-party/java/mapillary-sdk/sdk/bucklibs/okhttp-logging-interceptor/logging-interceptor-4.7.2.jar;fbandroid/first-party/java/mapillary-sdk/sdk/bucklibs/retrofit2-converter-moshi/converter-moshi-2.5.0.jar;fbandroid/first-party/java/mapillary-sdk/sdk/bucklibs/retrofit2_adapter_rxjava2/adapter-rxjava2-2.8.1.jar;fbandroid/first-party/java/mapillary-sdk/sdk/bucklibs/sanselan/sanselan-0.97-incubator.jar;fbandroid/java/com/facebook/codelayouts/codegen/android.jar;fbandroid/java/com/facebook/codelayouts/codegen/dom4j-1.6.1.jar;fbandroid/java/com/instagram/common/lifecycleannotationprocessor/javapoet-1.4.0.jar;third-party/java/androidx/annotation/annotation/1.5.0/annotation-1.5.0.jar;fbandroid/third-party/android/androidx/constraintlayout/constraintlayout-solver/2.0.4/constraintlayout-solver-2.0.4.jar;fbandroid/third-party/android/core-lambda-stubs/core-lambda-stubs.jar;fbandroid/third-party/android/databinding/4.0.0/baseAdapters/baseAdapters-4.0.0.jar;fbandroid/third-party/android/databinding/4.0.0/baseLibrary/baseLibrary-4.0.0.jar;fbandroid/third-party/android/databinding/4.0.0/baseLibrarySupport/baseLibrary-4.0.0.jar;fbandroid/third-party/android/databinding/4.0.0/exec/exec-4.0.0.jar;fbandroid/third-party/android/databinding/4.0.0/library/library-4.0.0.jar;fbandroid/third-party/android/databinding/4.0.0/viewbinding/viewbinding-4.0.0.jar;fbandroid/third-party/android/tools/annotations/26.4.0/annotations-26.4.0.jar;fbandroid/third-party/android/tools/build/jetifier/jetifier-core/1.0.0-beta04/jetifier-core-1.0.0-beta04.jar;fbandroid/third-party/auto-value-gson/auto-value-gson-annotations-0.8.0.jar;fbandroid/third-party/auto-value/auto-value-annotations-1.6.3.jar;fbandroid/third-party/google/api-client/calendar/google-api-services-calendar-v3-rev411-1.25.0.jar;fbandroid/third-party/google/api-client/google-api-client-1.31.2.jar;fbandroid/third-party/google/api-client/http-client-apache-v2/google-http-client-apache-v2-1.38.1.jar;fbandroid/third-party/google/api-client/http-client/google-http-client-1.38.1.jar;fbandroid/third-party/google/api-client/http-client/gson/google-http-client-gson-1.38.1.jar;fbandroid/third-party/google/api-client/oauth-client/google-oauth-client-1.31.4.jar;fbandroid/third-party/java/adm/amazon-device-messaging-1.1.0.jar;fbandroid/third-party/java/android-svg/androidsvg-1.4.jar;fbandroid/third-party/java/antlr/4.5.3/antlr4-all.jar;fbandroid/third-party/java/antlr/antlr4-4.7.1-SNAPSHOT-complete.jar;fbandroid/third-party/java/antlr/antlr4-runtime-4.7.1-SNAPSHOT.jar;fbandroid/third-party/java/apache-commons-collections4/commons-collections4-4.0.jar;fbandroid/third-party/java/apache-httpclient/httpclient-4.5.2.jar;fbandroid/third-party/java/apache-httpclient/httpcore-4.4.4.jar;fbandroid/third-party/java/apache-httpclient/httpmime-4.5.2.jar;fbandroid/third-party/java/asm/5.0.3/asm-debug-all-5.0.3.jar;fbandroid/third-party/java/asm/8.0.1/asm-8.0.1.jar;fbandroid/third-party/java/asm/9.0/asm-9.0.jar;fbandroid/third-party/java/asm/9.0/asm-analysis-9.0.jar;fbandroid/third-party/java/asm/9.0/asm-commons-9.0.jar;fbandroid/third-party/java/asm/9.0/asm-tree-9.0.jar;fbandroid/third-party/java/asm/9.0/asm-util-9.0.jar;fbandroid/third-party/java/asn-one/asn-one-nolog-0.4.0.jar;fbandroid/third-party/java/auto-common/auto-common.jar;fbandroid/third-party/java/bolts/bolts-applinks-1.4.0.jar;fbandroid/third-party/java/bolts/bolts-tasks-1.4.0.jar;fbandroid/third-party/java/bouncycastle/bcpkix-jdk15to18-163.jar;fbandroid/third-party/java/bouncycastle/bcprov-jdk15to18-163.jar;fbandroid/third-party/java/buck-tracing-api/tracing-api.jar;fbandroid/third-party/java/commons-codec/commons-codec-1.15.jar;fbandroid/third-party/java/commons-io/commons-io-2.4.jar;fbandroid/third-party/java/commons-logging/commons-logging-1.1.1.jar;fbandroid/third-party/java/eddsa/eddsa-0.2.0.jar;fbandroid/third-party/java/fest/fest-util-1.2.5.jar;fbandroid/third-party/java/glide/annotations-4.8.0.jar;fbandroid/third-party/java/glide/disklrucache-4.8.0.jar;fbandroid/third-party/java/grpc/grpc-context-1.24.0.jar;fbandroid/third-party/java/gson-converter/converter-gson-2.0.1.jar;third-party/java/gson/2.8.8/gson-2.8.8.jar;xplat/third-party/java/javax.annotation/javax.annotation-3.1.1.jar;fbandroid/third-party/java/javax-annotation/javax.annotation-api-1.3.2.jar;fbandroid/third-party/java/jaxb/javax-activation-api.jar;fbandroid/third-party/java/jcommander/jcommander-1.64.jar;fbandroid/third-party/java/joda/joda-time-2.3.jar;fbandroid/third-party/java/joda/joda-time-2.9.1.jar;fbandroid/third-party/java/jopt-simple/jopt-simple-4.6.jar;fbandroid/third-party/java/json/json-20090211.jar;fbandroid/third-party/java/jsr-250/jsr-250.jar;fbandroid/third-party/java/leakcanary/haha-1.3.jar;fbandroid/third-party/java/leakcanary/leakcanary-analyzer-1.3.1.jar;fbandroid/third-party/java/leakcanary/leakcanary-watcher-1.3.1.jar;fbandroid/third-party/java/leakcanaryv2/shark-2.4.jar;fbandroid/third-party/java/leakcanaryv2/shark-android-2.4.jar;fbandroid/third-party/java/leakcanaryv2/shark-graph-2.4.jar;fbandroid/third-party/java/leakcanaryv2/shark-hprof-2.4.jar;fbandroid/third-party/java/leakcanaryv2/shark-log-2.4.jar;fbandroid/third-party/java/libphonenumber-8.12.9/libphonenumber-8.12.9.jar;fbandroid/third-party/java/mediatek/mediatek-android-v1.0.jar;fbandroid/third-party/java/mediatek/mediatek-compatibility-v1.0.jar;fbandroid/third-party/java/moshi-converter/converter-moshi-2.0.1.jar;fbandroid/third-party/java/moshi/moshi-1.6.0.jar;fbandroid/third-party/java/moshi/moshi-kotlin-1.6.0.jar;fbandroid/third-party/java/mpandroidchart/mpandroidchart-v3.0.3.jar;fbandroid/third-party/java/okhttp/okhttp-2.7.5.jar;fbandroid/third-party/java/okhttp/okhttp-urlconnection-2.7.5.jar;fbandroid/third-party/java/okhttp/okhttp-urlconnection-3.6.0.jar;fbandroid/third-party/java/okio/okio-1.14.0.jar;fbandroid/third-party/java/okio/okio-1.15.0.jar;fbandroid/third-party/java/okio/okio-1.17.4.jar;fbandroid/third-party/java/okio/okio-2.6.0.jar;fbandroid/third-party/java/opencensus/opencensus-api-0.24.0.jar;fbandroid/third-party/java/opencensus/opencensus-contrib-http-util-0.24.0.jar;fbandroid/third-party/java/picasso/picasso-2.5.2.jar;fbandroid/third-party/java/protobuf/precompiled/protobuf-java-2.6.1.jar;fbandroid/third-party/java/retrofit/retrofit-1.9.0.jar;fbandroid/third-party/java/retrofit/retrofit-2.6.1.jar;fbandroid/third-party/java/seismic/seismic-1.0.3.jar;fbandroid/third-party/java/spongycastle/core-1.54.0.0.jar;fbandroid/third-party/java/spongycastle/pkix-1.54.0.0.jar;fbandroid/third-party/java/spongycastle/prov-1.54.0.0.jar;fbandroid/third-party/java/sqlite/sqlite-jdbc-3.8.11.2.jar;fbandroid/third-party/java/stetho/stetho-okhttp3.jar;fbandroid/third-party/java/stetho/stetho-urlconnection.jar;fbandroid/third-party/java/thrifty/thrifty-schema-1.0.0-RC2.jar;fbandroid/third-party/java/watls/watls-core-9f73d6718bb0163bb3d78703e6bb6c942efb965b.jar;fbandroid/third-party/java/websocket/Java-WebSocket-1.5.1-with-dependencies.jar;fbandroid/third-party/java/xz/xz-1.3.jar;fbandroid/third-party/java/yearclass/yearclass-2.1.0.jar;fbandroid/third-party/java/zxing/zxing-core-3.3.3.jar;fbandroid/third-party/mozilla/universalchardet/universalchardet.jar;fbandroid/third-party/org/xerial/sqlite-jdbc/3.25.2/sqlite-jdbc-3.25.2.jar;third-party/java/android-annotations/annotations-4.1.1.4.jar;third-party/java/androidx-annotation/annotation-1.1.0.jar;third-party/java/assertj/assertj-core-2.9.0.jar;third-party/java/cglib/cglib-nodep-2.2.jar;third-party/java/checkerframework/checker-compat-qual-2.5.3.jar;third-party/java/checkerframework/checker-qual-3.9.1.jar;third-party/java/commons-cli/commons-cli-1.3.1.jar;third-party/java/commons-lang3/commons-lang3-3.4.jar;third-party/java/javassist/javassist-3.25.0-GA.jar;third-party/java/mustache.java/mustache.java.jar;third-party/kotlin/1.4.32/lib/android-extensions-compiler.jar;third-party/kotlin/1.4.32/lib/android-extensions-runtime.jar;third-party/kotlin/1.4.32/lib/annotations-13.0.jar;third-party/kotlin/1.4.32/lib/kotlin-annotations-jvm.jar;third-party/kotlin/1.4.32/lib/kotlin-reflect.jar;third-party/kotlin/1.4.32/lib/kotlin-stdlib-jdk7.jar;third-party/kotlin/1.4.32/lib/kotlin-stdlib-jdk8.jar;third-party/kotlin/1.4.32/lib/kotlin-stdlib.jar;third-party/kotlin/1.4.32/lib/kotlinx-serialization-compiler-plugin.jar;third-party/kotlin/1.4.32/lib/trove4j.jar;third-party/kotlin/clikt/clikt-2.3.0.jar;third-party/kotlin/kotlinx/coroutines/1.4.3/kotlinx-coroutines-android-1.4.3.jar;third-party/kotlin/kotlinx/coroutines/1.4.3/kotlinx-coroutines-core-1.4.3.jar;third-party/kotlin/kotlinx/coroutines/1.4.3/kotlinx-coroutines-guava-1.4.3.jar;third-party/kotlin/kotlinx/coroutines/1.4.3/kotlinx-coroutines-test-1.4.3.jar;third-party/kotlin/kotlinx/serialization/kotlinx-serialization-core-jvm-1.1.0.jar;third-party/kotlin/kotlinx/serialization/kotlinx-serialization-json-jvm-1.1.0.jar;xplat/third-party/j2objc/lib/j2objc_annotations.jar;xplat/third-party/java/javapoet/javapoet-1.9.0.jar;xplat/third-party/java/javax.annotation/javax.annotation-api-1.3.2.jar;xplat/third-party/java/jsr-305/jsr305.jar;xplat/third-party/java/jsr-330/javax.inject.jar"
}
```

Also tested the --analyze-third-party stuff:
```
buck run //fbandroid/native/mariana-trench/shim:shim -- \
  --apk-path=$HOME/mariana-trench-apk/fbandroid/fblite_latest.apk \
  --output-directory=/tmp/output \
--verbosity 2 \
--analyze-third-party
File changed: fbsource//fbandroid/native/mariana-trench/facebook/shim/third_party_utils.py
Buck UI: https://www.internalfb.com/buck2/ee874d0d-6558-46a4-a828-91c0c85254ee
Network: Up: 0B  Down: 0B
Jobs completed: 1547. Time elapsed: 3.4s.
BUILD SUCCEEDED
/data/users/arthaud/fbsource/buck-out/v2/gen/fbsource/a2a1379d4dff3ee3/fbandroid/native/mariana-trench/shim/__shim__/shim#link-tree/pyredex/utils.py:12: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  import distutils.version
INFO Building `fbsource//fbandroid/native/mariana-trench:mariana-trench` with `fbandroid/mode/opt`...
INFO Extracting `/home/arthaud/mariana-trench-apk/fbandroid/fblite_latest.apk`...
INFO Extracted APK into `/tmp/tmpwwbbjil4_apk` and DEX into `/tmp/tmp171tppdw_dex`
INFO Running Mariana Trench: /packages/gogojail/gogojail -k -b/tmp,/tmp,ro -b/packages,/packages,ro -b/tmp/output/,/out,rwnx -- /data/users/arthaud/fbsource/buck-out/v2/gen/fbsource/dc2fcc3b00b88815/fbandroid/native/mariana-trench/__mariana-trench__/mariana-trench --config /tmp/tmpq_p2tsbj_resources/options.json
[..]
FileNotFoundError: [Errno 2] No such file or directory: '/packages/gogojail/gogojail'
```

Reviewed By: anwesht

Differential Revision: D60169773

Pulled By: arthaud

fbshipit-source-id: f8e42913e02e8c84b6acc8162e274c1738c351c5