Fix OSS build: update boost header
Summary:
OSS builds have been failing since ~26 days with errors:
```
[ 86%] Building CXX object CMakeFiles/mariana-trench-unit-tests.dir/source/tests/AccessPathTreeDomainTest.cpp.o
/Users/runner/work/mariana-trench/mariana-trench/source/tests/integration/models/IntegrationTest.cpp:435:22: error: no member named 'load_string_file' in namespace 'boost::filesystem'
  boost::filesystem::load_string_file(path, unparsed_source);
  ~~~~~~~~~~~~~~~~~~~^
/Users/runner/work/mariana-trench/mariana-trench/source/tests/integration/models/IntegrationTest.cpp:553:24: error: no member named 'load_string_file' in namespace 'boost::filesystem'
    boost::filesystem::load_string_file(expected_path, expected_output);
    ~~~~~~~~~~~~~~~~~~~^
/Users/runner/work/mariana-trench/mariana-trench/source/tests/integration/models/IntegrationTest.cpp:561:24: error: no member named 'save_string_file' in namespace 'boost::filesystem'
    boost::filesystem::save_string_file(
    ~~~~~~~~~~~~~~~~~~~^
3 errors generated.
```

Looks like the [latest boost version](https://www.boost.org/users/history/version_1_79_0.html) deprecated these and are not included by default:
> Deprecated: boost/filesystem/string_file.hpp header is deprecated and will be removed in a future release. The header is no longer included by boost/filesystem.hpp by default. Users are advised to implement the functionality themselves or migrate to other implementations.

Bandaid till its completely removed in the future.

Reviewed By: dkgi

Differential Revision: D38714580

fbshipit-source-id: 28a2ccffd2a8b83b798ad815a937905aa909f271